"""
Module D — Remediation Script Generator
Generates actionable remediation scripts based on scan results:
  - UFW firewall rules (Bash)
  - SSH hardening config (Bash)
  - FastAPI security headers middleware (Python)
  - Dependency upgrade commands (Bash)
"""

import os
from datetime import datetime
from typing import Any

from scanner.constants import PORT_NAMES


# ---------------------------------------------------------------------------
# Script templates
# ---------------------------------------------------------------------------

_UFW_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  UFW Firewall — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

echo "[*] Configuring UFW firewall..."

# Reset and set default policies
ufw --force reset
ufw default deny incoming
ufw default allow outgoing

# Allow essential services
ufw allow 80/tcp   comment 'HTTP'
ufw allow 443/tcp  comment 'HTTPS'
ufw allow 22/tcp   comment 'SSH (restrict to your IP in production)'

{deny_rules}

# Enable firewall
ufw --force enable
ufw status verbose

echo "[+] UFW configuration complete."
"""

_UFW_DENY_RULE = "ufw deny {port}/tcp  comment 'Block {service} — exposed in audit'"

_SSH_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  SSH Hardening — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

SSHD_CONFIG="/etc/ssh/sshd_config"

echo "[*] Hardening SSH configuration..."

# Backup original config
cp "$SSHD_CONFIG" "${{SSHD_CONFIG}}.bak.$(date +%Y%m%d%H%M%S)"

# Apply hardening settings
declare -A SSH_SETTINGS=(
    ["PasswordAuthentication"]="no"
    ["PubkeyAuthentication"]="yes"
    ["PermitRootLogin"]="no"
    ["X11Forwarding"]="no"
    ["MaxAuthTries"]="3"
    ["LoginGraceTime"]="30"
    ["Protocol"]="2"
    ["PermitEmptyPasswords"]="no"
    ["ClientAliveInterval"]="300"
    ["ClientAliveCountMax"]="2"
)

for KEY in "${{!SSH_SETTINGS[@]}}"; do
    VALUE="${{SSH_SETTINGS[$KEY]}}"
    if grep -qE "^#?\\s*${{KEY}}\\s" "$SSHD_CONFIG"; then
        sed -i "s|^#\\?\\s*${{KEY}}\\s.*|${{KEY}} ${{VALUE}}|" "$SSHD_CONFIG"
    else
        echo "${{KEY}} ${{VALUE}}" >> "$SSHD_CONFIG"
    fi
done

# Validate config before restarting
sshd -t && systemctl restart ssh

echo "[+] SSH hardening complete. Password auth is now DISABLED."
echo "[!] Make sure your SSH key is installed before closing this session."
"""

_FASTAPI_TEMPLATE = '''\
"""
FastAPI Security Headers Middleware
Auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}

USAGE
-----
Copy this file into your FastAPI project and register the middleware
in your main application file:

    from security_middleware import add_security_headers
    app.middleware("http")(add_security_headers)

Or as a class-based middleware (alternative):

    from starlette.middleware.base import BaseHTTPMiddleware
    app.add_middleware(SecurityHeadersMiddleware)
"""

from fastapi import Request, Response
from fastapi.responses import Response as FastAPIResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp


# ---------------------------------------------------------------------------
# Function-based middleware (simpler, recommended)
# ---------------------------------------------------------------------------
async def add_security_headers(request: Request, call_next) -> FastAPIResponse:
    """Add security headers to every HTTP response."""
    response: FastAPIResponse = await call_next(request)
{header_lines_4}
    return response


# ---------------------------------------------------------------------------
# Class-based middleware (alternative)
# ---------------------------------------------------------------------------
class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
{header_lines_8}
        return response
'''

_HEADER_VALUES: dict[str, str] = {
    "Content-Security-Policy":   "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'",
    "X-Frame-Options":           "DENY",
    "X-Content-Type-Options":    "nosniff",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "Referrer-Policy":           "strict-origin-when-cross-origin",
    "Permissions-Policy":        "geolocation=(), microphone=(), camera=()",
}

_UPGRADE_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  Dependency Upgrades — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

echo "[*] Upgrading vulnerable dependencies..."

{pip_commands}
{npm_commands}

echo "[+] Dependency upgrades complete."
echo "[!] Run your test suite after upgrading to ensure nothing is broken."
"""


# ---------------------------------------------------------------------------
# Internal builders
# ---------------------------------------------------------------------------

def _build_ufw_script(target: str, date: str, critical_ports: list[int]) -> str:
    deny_rules = ""
    for port in critical_ports:
        service = PORT_NAMES.get(port, "unknown")
        deny_rules += _UFW_DENY_RULE.format(port=port, service=service) + "\n"
    return _UFW_TEMPLATE.format(date=date, target=target, deny_rules=deny_rules.rstrip())


def _build_ssh_script(target: str, date: str) -> str:
    return _SSH_TEMPLATE.format(date=date, target=target)


def _build_fastapi_middleware(target: str, date: str, missing_headers: list[str]) -> str:
    headers_to_add = missing_headers if missing_headers else list(_HEADER_VALUES.keys())
    lines_4: list[str] = []
    lines_8: list[str] = []
    for header in headers_to_add:
        value = _HEADER_VALUES.get(header, "")
        if value:
            lines_4.append(f'    response.headers["{header}"] = "{value}"')
            lines_8.append(f'        response.headers["{header}"] = "{value}"')
    fallback_4 = '    pass  # All security headers already present'
    fallback_8 = '        pass  # All security headers already present'
    return _FASTAPI_TEMPLATE.format(
        date=date,
        target=target,
        header_lines_4="\n".join(lines_4) if lines_4 else fallback_4,
        header_lines_8="\n".join(lines_8) if lines_8 else fallback_8,
    )


def _build_upgrade_script(target: str, date: str, vulns: list[dict[str, Any]]) -> str:
    pip_lines: list[str] = []
    npm_lines: list[str] = []

    seen: set[str] = set()
    for vuln in vulns:
        pkg = vuln.get("package", "")
        eco = vuln.get("ecosystem", "")
        if not pkg or pkg in seen:
            continue
        seen.add(pkg)
        cve_str = ", ".join(vuln.get("cve_ids", []))
        comment = f"# {cve_str}" if cve_str else ""
        if eco == "PyPI":
            pip_lines.append(f"pip install --upgrade {pkg}  {comment}".rstrip())
        elif eco == "npm":
            npm_lines.append(f"npm update {pkg}  {comment}".rstrip())

    pip_block = "\n".join(pip_lines) if pip_lines else "# No PyPI vulnerabilities found"
    npm_block = "\n".join(npm_lines) if npm_lines else "# No npm vulnerabilities found"
    return _UPGRADE_TEMPLATE.format(date=date, target=target, pip_commands=pip_block, npm_commands=npm_block)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_remediation(
    target_url: str,
    port_result: dict[str, Any] | None = None,
    headers_result: dict[str, Any] | None = None,
    sca_result: dict[str, Any] | None = None,
    output_dir: str = "remediation",
) -> dict[str, str]:
    """
    Generate remediation scripts based on scan results.

    Args:
        target_url:     The scanned URL (used in script headers).
        port_result:    Dict from scan_ports() — used for UFW rules.
        headers_result: Dict from check_headers() — used for FastAPI middleware.
        sca_result:     Dict from check_sca() — used for upgrade commands.
        output_dir:     Directory where scripts will be written.

    Returns:
        A dict mapping script name → file path for each generated file.
    """
    os.makedirs(output_dir, exist_ok=True)
    date = datetime.now().strftime("%Y-%m-%d %H:%M")
    generated: dict[str, str] = {}

    # UFW script — always generated; includes deny rules for critical ports if found
    critical_ports: list[int] = []
    if port_result and not port_result.get("error"):
        critical_ports = port_result.get("critical_ports", [])
    ufw_path = os.path.join(output_dir, "ufw_setup.sh")
    with open(ufw_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(_build_ufw_script(target_url, date, critical_ports))
    generated["ufw"] = ufw_path

    # SSH hardening script — always generated
    ssh_path = os.path.join(output_dir, "ssh_hardening.sh")
    with open(ssh_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(_build_ssh_script(target_url, date))
    generated["ssh"] = ssh_path

    # FastAPI middleware — generated when headers are missing
    missing_headers: list[str] = []
    if headers_result and not headers_result.get("error"):
        missing_headers = headers_result.get("headers_missing", [])
    if missing_headers or not headers_result:
        middleware_path = os.path.join(output_dir, "fastapi_security_middleware.py")
        with open(middleware_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(_build_fastapi_middleware(target_url, date, missing_headers))
        generated["fastapi"] = middleware_path

    # Dependency upgrade script — generated when CVEs are found
    vulns: list[dict[str, Any]] = []
    if sca_result and not sca_result.get("error"):
        vulns = sca_result.get("vulns", [])
    if vulns or sca_result:
        upgrade_path = os.path.join(output_dir, "upgrade_deps.sh")
        with open(upgrade_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(_build_upgrade_script(target_url, date, vulns))
        generated["upgrade"] = upgrade_path

    return generated
