"""
Module D — Remediation Script Generator
Generates actionable remediation scripts based on scan results:
  - UFW firewall rules (Bash)
  - SSH hardening config (Bash)
  - FastAPI security headers middleware (Python)
  - Dependency upgrade commands (Bash)
  - Nginx SSL/TLS hardening config
  - CORS fix snippet (FastAPI + Nginx)
  - Cookie security fix (FastAPI middleware)
  - HTTP methods restriction (Nginx)
  - Clickjacking protection (Nginx + FastAPI)
  - Directory listing disable (Nginx)
  - Open redirect protection (FastAPI middleware)
  - robots.txt template
  - DNS email security (SPF/DKIM/DMARC) instructions
  - WAF / rate-limiting (Nginx)
"""

import os
from datetime import datetime
from typing import Any

from scanner.constants import PORT_NAMES


# ---------------------------------------------------------------------------
# Script templates
# ---------------------------------------------------------------------------

_UFW_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  UFW Firewall — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

echo "[*] Configuring UFW firewall..."

# Reset and set default policies
ufw --force reset
ufw default deny incoming
ufw default allow outgoing

# Allow essential services
ufw allow 80/tcp   comment 'HTTP'
ufw allow 443/tcp  comment 'HTTPS'
ufw allow 22/tcp   comment 'SSH (restrict to your IP in production)'

{deny_rules}

# Enable firewall
ufw --force enable
ufw status verbose

echo "[+] UFW configuration complete."
"""

_UFW_DENY_RULE = "ufw deny {port}/tcp  comment 'Block {service} — exposed in audit'"

_SSH_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  SSH Hardening — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

SSHD_CONFIG="/etc/ssh/sshd_config"

echo "[*] Hardening SSH configuration..."

# Backup original config
cp "$SSHD_CONFIG" "${{SSHD_CONFIG}}.bak.$(date +%Y%m%d%H%M%S)"

# Apply hardening settings
declare -A SSH_SETTINGS=(
    ["PasswordAuthentication"]="no"
    ["PubkeyAuthentication"]="yes"
    ["PermitRootLogin"]="no"
    ["X11Forwarding"]="no"
    ["MaxAuthTries"]="3"
    ["LoginGraceTime"]="30"
    ["Protocol"]="2"
    ["PermitEmptyPasswords"]="no"
    ["ClientAliveInterval"]="300"
    ["ClientAliveCountMax"]="2"
)

for KEY in "${{!SSH_SETTINGS[@]}}"; do
    VALUE="${{SSH_SETTINGS[$KEY]}}"
    if grep -qE "^#?\\s*${{KEY}}\\s" "$SSHD_CONFIG"; then
        sed -i "s|^#\\?\\s*${{KEY}}\\s.*|${{KEY}} ${{VALUE}}|" "$SSHD_CONFIG"
    else
        echo "${{KEY}} ${{VALUE}}" >> "$SSHD_CONFIG"
    fi
done

# Validate config before restarting
sshd -t && systemctl restart ssh

echo "[+] SSH hardening complete. Password auth is now DISABLED."
echo "[!] Make sure your SSH key is installed before closing this session."
"""

_FASTAPI_TEMPLATE = '''\
"""
FastAPI Security Headers Middleware
Auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}

USAGE
-----
Copy this file into your FastAPI project and register the middleware
in your main application file:

    from security_middleware import add_security_headers
    app.middleware("http")(add_security_headers)

Or as a class-based middleware (alternative):

    from starlette.middleware.base import BaseHTTPMiddleware
    app.add_middleware(SecurityHeadersMiddleware)
"""

from fastapi import Request, Response
from fastapi.responses import Response as FastAPIResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp


# ---------------------------------------------------------------------------
# Function-based middleware (simpler, recommended)
# ---------------------------------------------------------------------------
async def add_security_headers(request: Request, call_next) -> FastAPIResponse:
    """Add security headers to every HTTP response."""
    response: FastAPIResponse = await call_next(request)
{header_lines_4}
    return response


# ---------------------------------------------------------------------------
# Class-based middleware (alternative)
# ---------------------------------------------------------------------------
class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
{header_lines_8}
        return response
'''

_HEADER_VALUES: dict[str, str] = {
    "Content-Security-Policy":   "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'",
    "X-Frame-Options":           "DENY",
    "X-Content-Type-Options":    "nosniff",
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "Referrer-Policy":           "strict-origin-when-cross-origin",
    "Permissions-Policy":        "geolocation=(), microphone=(), camera=()",
}

_UPGRADE_TEMPLATE = """\
#!/usr/bin/env bash
# ============================================================
#  Dependency Upgrades — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
set -euo pipefail

echo "[*] Upgrading vulnerable dependencies..."

{pip_commands}
{npm_commands}

echo "[+] Dependency upgrades complete."
echo "[!] Run your test suite after upgrading to ensure nothing is broken."
"""

_SSL_NGINX_TEMPLATE = """\
# ============================================================
#  Nginx SSL/TLS Hardening — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
#
#  Place this inside your server {{ }} block or include it.
# ============================================================

# Only allow TLS 1.2 and 1.3
ssl_protocols TLSv1.2 TLSv1.3;

# Strong cipher suites (forward secrecy + AEAD)
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
ssl_prefer_server_ciphers off;

# HSTS — force HTTPS for 1 year, include subdomains
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 8.8.8.8 valid=300s;
resolver_timeout 5s;

# DH params (generate with: openssl dhparam -out /etc/nginx/dhparam.pem 4096)
ssl_dhparam /etc/nginx/dhparam.pem;

# Session settings
ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

# Redirect HTTP → HTTPS
server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}
"""

_CORS_FASTAPI_TEMPLATE = '''\
"""
FastAPI CORS Fix — auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}

ISSUE DETECTED
--------------
{cors_issues}

FIX
---
Replace your current CORS middleware with the secure configuration below.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI()

# ✅ Secure CORS configuration
# Replace the origins list with your actual frontend domain(s).
# NEVER use allow_origins=["*"] with allow_credentials=True.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://{domain}",         # production frontend
        # "https://staging.{domain}",  # staging (uncomment if needed)
    ],
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH"],
    allow_headers=["Authorization", "Content-Type", "X-Requested-With"],
    expose_headers=["X-Total-Count"],
    max_age=600,
)
'''

_CORS_NGINX_TEMPLATE = """\
# ============================================================
#  Nginx CORS Fix — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
# Add inside your location block (e.g. location /api/ {{ ... }})

# Only allow your frontend origin — replace with your actual domain
set $cors_origin "";
if ($http_origin = "https://{domain}") {{
    set $cors_origin $http_origin;
}}

add_header Access-Control-Allow-Origin  $cors_origin always;
add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;
add_header Access-Control-Allow-Credentials "true" always;

# Handle preflight
if ($request_method = OPTIONS) {{
    add_header Access-Control-Max-Age 600;
    return 204;
}}
"""

_COOKIES_TEMPLATE = '''\
"""
FastAPI Secure Cookie Middleware — auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}

ISSUES DETECTED
---------------
{cookie_issues}

FIX
---
This middleware rewrites Set-Cookie headers to add missing security flags.
Add it to your FastAPI app:

    from cookie_security import SecureCookieMiddleware
    app.add_middleware(SecureCookieMiddleware)
"""

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


class SecureCookieMiddleware(BaseHTTPMiddleware):
    """Enforce HttpOnly, Secure, and SameSite=Strict on all Set-Cookie headers."""

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
        new_cookies = []
        for cookie in response.headers.getlist("set-cookie"):
            cookie = self._enforce_flags(cookie)
            new_cookies.append(cookie)
        if new_cookies:
            # Replace all Set-Cookie headers
            headers = list(response.headers.items())
            headers = [(k, v) for k, v in headers if k.lower() != "set-cookie"]
            for c in new_cookies:
                headers.append(("set-cookie", c))
            response.headers.__dict__["_list"] = headers
        return response

    @staticmethod
    def _enforce_flags(cookie: str) -> str:
        parts = [part.strip() for part in cookie.split(";")]
        flags = {{part.lower().split("=")[0]: part for part in parts[1:]}}

        if "httponly" not in flags:
            parts.append("HttpOnly")
        if "secure" not in flags:
            parts.append("Secure")
        if "samesite" not in flags:
            parts.append("SameSite=Strict")

        return "; ".join(parts)
'''

_HTTP_METHODS_TEMPLATE = """\
# ============================================================
#  Nginx — Restrict Dangerous HTTP Methods
#  Auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
#
#  DANGEROUS METHODS DETECTED: {dangerous_methods}
# ============================================================
# Add inside your server {{ }} or location {{ }} block.

# Allow only safe methods — adjust if your API uses PUT/DELETE legitimately
if ($request_method !~ ^(GET|POST|HEAD|OPTIONS)$) {{
    return 405;
}}

# Specifically block TRACE (XST attack vector)
if ($request_method = TRACE) {{
    return 405;
}}
"""

_CLICKJACKING_NGINX_TEMPLATE = """\
# ============================================================
#  Nginx — Clickjacking Protection
#  Auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
# Add inside your server {{ }} block.

# Prevent framing by any external site
add_header X-Frame-Options "DENY" always;

# Modern CSP alternative — more flexible
add_header Content-Security-Policy "frame-ancestors 'none'" always;
"""

_CLICKJACKING_FASTAPI_TEMPLATE = '''\
"""
FastAPI Clickjacking Protection — auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}
"""

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


class ClickjackingMiddleware(BaseHTTPMiddleware):
    """Add X-Frame-Options and CSP frame-ancestors to all responses."""

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Content-Security-Policy"] = "frame-ancestors \'none\'"
        return response
'''

_DIRECTORY_LISTING_TEMPLATE = """\
# ============================================================
#  Nginx — Disable Directory Listing
#  Auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
#
#  EXPOSED PATHS: {exposed_paths}
# ============================================================
# Add inside your server {{ }} block or the relevant location block.

# Disable directory listing globally
autoindex off;

# Deny access to hidden files (.env, .git, etc.)
location ~ /\\. {{
    deny all;
    return 404;
}}

# Deny access to sensitive files
location ~* \\.(env|git|svn|htpasswd|DS_Store|bak|sql|log)$ {{
    deny all;
    return 404;
}}
"""

_OPEN_REDIRECT_TEMPLATE = '''\
"""
FastAPI Open Redirect Protection — auto-generated by Cyber-Scanner v1.0
Generated : {date}
Target    : {target}

USAGE
-----
Use safe_redirect() instead of RedirectResponse() for user-supplied URLs.
"""

from urllib.parse import urlparse
from fastapi import HTTPException
from fastapi.responses import RedirectResponse

# Allowlist of trusted redirect domains
ALLOWED_DOMAINS: set[str] = {{
    "{domain}",
    # Add other trusted domains here
}}


def safe_redirect(url: str, status_code: int = 302) -> RedirectResponse:
    """
    Safely redirect to a URL, rejecting external domains not in the allowlist.

    Args:
        url:         The target URL (user-supplied or internal).
        status_code: HTTP status code (302 by default).

    Raises:
        HTTPException 400 if the redirect target is not allowed.
    """
    parsed = urlparse(url)

    # Allow relative URLs (no scheme/netloc)
    if not parsed.scheme and not parsed.netloc:
        return RedirectResponse(url=url, status_code=status_code)

    # Reject external domains not in the allowlist
    if parsed.netloc not in ALLOWED_DOMAINS:
        raise HTTPException(
            status_code=400,
            detail=f"Redirect to '{{parsed.netloc}}' is not allowed.",
        )

    return RedirectResponse(url=url, status_code=status_code)
'''

_ROBOTS_TEMPLATE = """\
# ============================================================
#  robots.txt — Security-hardened template
#  Auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================

# Allow all crawlers on public content
User-agent: *
Allow: /

# Disallow sensitive paths
Disallow: /admin/
Disallow: /api/
Disallow: /private/
Disallow: /internal/
Disallow: /config/
Disallow: /backup/
Disallow: /.env
Disallow: /.git/
Disallow: /uploads/

# Disallow query strings that may expose internal params
Disallow: /*?debug=
Disallow: /*?token=
Disallow: /*?key=

# Sitemap (update with your actual sitemap URL)
Sitemap: https://{domain}/sitemap.xml
"""

_EMAIL_SECURITY_TEMPLATE = """\
# ============================================================
#  Email Security (SPF / DKIM / DMARC) DNS Records
#  Auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
#
#  ISSUES DETECTED:
{email_issues_comment}
# ============================================================
#
#  Add the following DNS TXT records to your domain registrar
#  or DNS provider (Route 53, Cloudflare, OVH, etc.)
#
# ------------------------------------------------------------

## 1. SPF — Sender Policy Framework
## Specifies which mail servers are authorised to send email for your domain.
## Replace "ip4:YOUR_SERVER_IP" with your actual mail server IP.

TXT  @   "v=spf1 ip4:YOUR_SERVER_IP include:_spf.google.com ~all"

# Common includes:
#   include:_spf.google.com      (Google Workspace)
#   include:sendgrid.net         (SendGrid)
#   include:amazonses.com        (Amazon SES)
# Use ~all (softfail) initially, switch to -all (hardfail) after validation.


## 2. DKIM — DomainKeys Identified Mail
## Cryptographic signature to verify mail authenticity.
## Generate your DKIM key pair with your mail provider and add:

TXT  mail._domainkey   "v=DKIM1; k=rsa; p=YOUR_PUBLIC_KEY_HERE"

# Steps:
#   1. Generate key pair: openssl genrsa -out dkim_private.key 2048
#   2. Extract public key: openssl rsa -in dkim_private.key -pubout -out dkim_public.key
#   3. Configure your MTA (Postfix/OpenDKIM) with the private key.
#   4. Add the public key to DNS as shown above.


## 3. DMARC — Domain-based Message Authentication
## Tells receiving servers what to do with unauthenticated email.

TXT  _dmarc   "v=DMARC1; p=quarantine; rua=mailto:dmarc-reports@{domain}; ruf=mailto:dmarc-forensics@{domain}; pct=100; adkim=s; aspf=s"

# Recommended policy progression:
#   p=none       → monitoring only (start here)
#   p=quarantine → send failing mail to spam
#   p=reject     → reject failing mail entirely (most secure)
"""

_WAF_NGINX_TEMPLATE = """\
# ============================================================
#  Nginx WAF / Rate Limiting — auto-generated by Cyber-Scanner v1.0
#  Generated : {date}
#  Target    : {target}
# ============================================================
# Add the limit_req_zone directives in the http {{ }} block of nginx.conf,
# and the limit_req directives inside your server/location blocks.

# ── In http {{ }} block (nginx.conf) ────────────────────────────────────────

# Rate limit zones
limit_req_zone $binary_remote_addr zone=api_limit:10m    rate=30r/m;
limit_req_zone $binary_remote_addr zone=login_limit:10m  rate=5r/m;
limit_req_zone $binary_remote_addr zone=global_limit:10m rate=100r/m;

# Connection limit
limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

# ── In server {{ }} or location {{ }} block ──────────────────────────────────

# Global rate limit
limit_req zone=global_limit burst=20 nodelay;
limit_conn conn_limit 20;

# Stricter limit on API endpoints
location /api/ {{
    limit_req zone=api_limit burst=10 nodelay;
    limit_req_status 429;
    proxy_pass http://backend;
}}

# Very strict limit on authentication endpoints
location /api/auth/ {{
    limit_req zone=login_limit burst=3 nodelay;
    limit_req_status 429;
    proxy_pass http://backend;
}}

# Block common attack patterns
location ~* (union|select|insert|drop|exec|script|eval|base64_decode) {{
    return 403;
}}

# Block access to hidden files and sensitive paths
location ~ /\\. {{
    deny all;
    return 404;
}}

# Security headers
add_header X-Content-Type-Options  "nosniff"                        always;
add_header X-Frame-Options          "DENY"                           always;
add_header X-XSS-Protection         "1; mode=block"                  always;
add_header Referrer-Policy          "strict-origin-when-cross-origin" always;
"""


# ---------------------------------------------------------------------------
# Internal builders
# ---------------------------------------------------------------------------

def _build_ufw_script(target: str, date: str, critical_ports: list[int]) -> str:
    deny_rules = ""
    for port in critical_ports:
        service = PORT_NAMES.get(port, "unknown")
        deny_rules += _UFW_DENY_RULE.format(port=port, service=service) + "\n"
    return _UFW_TEMPLATE.format(date=date, target=target, deny_rules=deny_rules.rstrip())


def _build_ssh_script(target: str, date: str) -> str:
    return _SSH_TEMPLATE.format(date=date, target=target)


def _build_fastapi_middleware(target: str, date: str, missing_headers: list[str]) -> str:
    headers_to_add = missing_headers if missing_headers else list(_HEADER_VALUES.keys())
    lines_4: list[str] = []
    lines_8: list[str] = []
    for header in headers_to_add:
        value = _HEADER_VALUES.get(header, "")
        if value:
            lines_4.append(f'    response.headers["{header}"] = "{value}"')
            lines_8.append(f'        response.headers["{header}"] = "{value}"')
    fallback_4 = '    pass  # All security headers already present'
    fallback_8 = '        pass  # All security headers already present'
    return _FASTAPI_TEMPLATE.format(
        date=date,
        target=target,
        header_lines_4="\n".join(lines_4) if lines_4 else fallback_4,
        header_lines_8="\n".join(lines_8) if lines_8 else fallback_8,
    )


def _build_upgrade_script(target: str, date: str, vulns: list[dict[str, Any]]) -> str:
    pip_lines: list[str] = []
    npm_lines: list[str] = []

    seen: set[str] = set()
    for vuln in vulns:
        pkg = vuln.get("package", "")
        eco = vuln.get("ecosystem", "")
        if not pkg or pkg in seen:
            continue
        seen.add(pkg)
        cve_str = ", ".join(vuln.get("cve_ids", []))
        comment = f"# {cve_str}" if cve_str else ""
        if eco == "PyPI":
            pip_lines.append(f"pip install --upgrade {pkg}  {comment}".rstrip())
        elif eco == "npm":
            npm_lines.append(f"npm update {pkg}  {comment}".rstrip())

    pip_block = "\n".join(pip_lines) if pip_lines else "# No PyPI vulnerabilities found"
    npm_block = "\n".join(npm_lines) if npm_lines else "# No npm vulnerabilities found"
    return _UPGRADE_TEMPLATE.format(date=date, target=target, pip_commands=pip_block, npm_commands=npm_block)


def _extract_domain(target_url: str) -> str:
    """Extract bare domain from a URL (e.g. 'https://example.com/path' → 'example.com')."""
    from urllib.parse import urlparse
    parsed = urlparse(target_url)
    return parsed.netloc or target_url


def _build_ssl_nginx(target: str, date: str) -> str:
    domain = _extract_domain(target)
    return _SSL_NGINX_TEMPLATE.format(date=date, target=target, domain=domain)


def _build_cors_fastapi(target: str, date: str, issues: list[str]) -> str:
    domain = _extract_domain(target)
    issues_str = "\n".join(f"  - {i}" for i in issues) if issues else "  - Wildcard CORS origin detected"
    return _CORS_FASTAPI_TEMPLATE.format(date=date, target=target, domain=domain, cors_issues=issues_str)


def _build_cors_nginx(target: str, date: str) -> str:
    domain = _extract_domain(target)
    return _CORS_NGINX_TEMPLATE.format(date=date, target=target, domain=domain)


def _build_cookies_script(target: str, date: str, issues: list[dict[str, Any]]) -> str:
    if issues:
        lines = []
        for i in issues[:10]:
            name = i.get("name") or i.get("cookie", "?")
            detail = i.get("issue") or ", ".join(i.get("missing_flags", [])) or "unknown"
            lines.append(f"  - Cookie '{name}': {detail}")
        issues_str = "\n".join(lines)
    else:
        issues_str = "  - Missing HttpOnly / Secure / SameSite flags on session cookies"
    return _COOKIES_TEMPLATE.format(date=date, target=target, cookie_issues=issues_str)


def _build_http_methods_nginx(target: str, date: str, dangerous_methods: list[str]) -> str:
    methods_str = ", ".join(dangerous_methods) if dangerous_methods else "TRACE, PUT, DELETE"
    return _HTTP_METHODS_TEMPLATE.format(date=date, target=target, dangerous_methods=methods_str)


def _build_clickjacking_nginx(target: str, date: str) -> str:
    return _CLICKJACKING_NGINX_TEMPLATE.format(date=date, target=target)


def _build_clickjacking_fastapi(target: str, date: str) -> str:
    return _CLICKJACKING_FASTAPI_TEMPLATE.format(date=date, target=target)


def _build_directory_listing_nginx(target: str, date: str, exposed: list[str]) -> str:
    paths_str = ", ".join(exposed[:5]) if exposed else "unknown paths"
    return _DIRECTORY_LISTING_TEMPLATE.format(date=date, target=target, exposed_paths=paths_str)


def _build_open_redirect_fastapi(target: str, date: str) -> str:
    domain = _extract_domain(target)
    return _OPEN_REDIRECT_TEMPLATE.format(date=date, target=target, domain=domain)


def _build_robots_txt(target: str, date: str) -> str:
    domain = _extract_domain(target)
    return _ROBOTS_TEMPLATE.format(date=date, target=target, domain=domain)


def _build_email_security(target: str, date: str, email_result: dict[str, Any]) -> str:
    domain = _extract_domain(target)
    issues: list[str] = []

    def _missing(field: str) -> bool:
        val = email_result.get(field)
        if isinstance(val, dict):
            return not val.get("valid") and not val.get("found")
        return not val  # bool False or None → missing

    if _missing("spf"):
        issues.append("SPF record missing or invalid")
    if _missing("dkim"):
        issues.append("DKIM record not found")
    if _missing("dmarc"):
        issues.append("DMARC record missing or invalid")
    comment_lines = "\n".join(f"#    - {i}" for i in issues) if issues else "#    - Email security records not fully configured"
    return _EMAIL_SECURITY_TEMPLATE.format(date=date, target=target, domain=domain, email_issues_comment=comment_lines)


def _build_waf_nginx(target: str, date: str) -> str:
    return _WAF_NGINX_TEMPLATE.format(date=date, target=target)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_remediation(
    target_url: str,
    port_result: dict[str, Any] | None = None,
    headers_result: dict[str, Any] | None = None,
    sca_result: dict[str, Any] | None = None,
    ssl_result: dict[str, Any] | None = None,
    cors_result: dict[str, Any] | None = None,
    cookie_result: dict[str, Any] | None = None,
    http_methods_result: dict[str, Any] | None = None,
    clickjacking_result: dict[str, Any] | None = None,
    directory_listing_result: dict[str, Any] | None = None,
    open_redirect_result: dict[str, Any] | None = None,
    robots_result: dict[str, Any] | None = None,
    email_result: dict[str, Any] | None = None,
    waf_result: dict[str, Any] | None = None,
    output_dir: str = "remediation",
) -> dict[str, str]:
    """
    Generate remediation scripts based on scan results.

    Returns a dict mapping script name → file path for each generated file.
    Scripts are only generated when the corresponding result indicates an issue
    (status WARNING or CRITICAL), except for always-generated scripts.
    """
    os.makedirs(output_dir, exist_ok=True)
    date = datetime.now().strftime("%Y-%m-%d %H:%M")
    generated: dict[str, str] = {}

    def _write(filename: str, content: str, key: str) -> None:
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        generated[key] = path

    def _is_issue(result: dict[str, Any] | None) -> bool:
        if result is None:
            return False
        return result.get("status") in ("WARNING", "CRITICAL")

    # ── Always generated ──────────────────────────────────────────────────────

    critical_ports: list[int] = []
    if port_result and not port_result.get("error"):
        critical_ports = port_result.get("critical_ports", [])
    _write("ufw_setup.sh", _build_ufw_script(target_url, date, critical_ports), "ufw")
    _write("ssh_hardening.sh", _build_ssh_script(target_url, date), "ssh")
    _write("robots.txt", _build_robots_txt(target_url, date), "robots")
    _write("nginx_waf_ratelimit.conf", _build_waf_nginx(target_url, date), "nginx_waf")

    # ── Conditional on issue ──────────────────────────────────────────────────

    # Security headers middleware
    missing_headers: list[str] = []
    if headers_result and not headers_result.get("error"):
        missing_headers = headers_result.get("headers_missing", [])
    if missing_headers or not headers_result:
        _write("fastapi_security_middleware.py", _build_fastapi_middleware(target_url, date, missing_headers), "fastapi")

    # Dependency upgrades
    vulns: list[dict[str, Any]] = []
    if sca_result and not sca_result.get("error"):
        vulns = sca_result.get("vulns", [])
    if vulns or sca_result:
        _write("upgrade_deps.sh", _build_upgrade_script(target_url, date, vulns), "upgrade")

    # SSL/TLS hardening
    if _is_issue(ssl_result):
        _write("nginx_ssl_hardening.conf", _build_ssl_nginx(target_url, date), "nginx_ssl")

    # CORS fix
    if _is_issue(cors_result):
        cors_issues = (cors_result or {}).get("issues", [])
        _write("fastapi_cors_fix.py", _build_cors_fastapi(target_url, date, cors_issues), "fastapi_cors")
        _write("nginx_cors_fix.conf", _build_cors_nginx(target_url, date), "nginx_cors")

    # Cookie security
    if _is_issue(cookie_result):
        cookie_issues = (cookie_result or {}).get("issues", [])
        _write("fastapi_cookie_security.py", _build_cookies_script(target_url, date, cookie_issues), "fastapi_cookie")

    # HTTP methods restriction
    if _is_issue(http_methods_result):
        result_dict = http_methods_result or {}
        # Support both {"dangerous_methods": [...]} and {"results": [{method, allowed}, ...]}
        if "dangerous_methods" in result_dict:
            dangerous = result_dict["dangerous_methods"]
        else:
            dangerous = [
                r.get("method", "") for r in result_dict.get("results", [])
                if r.get("allowed") and r.get("method") in {"TRACE", "PUT", "DELETE"}
            ]
        _write("nginx_http_methods.conf", _build_http_methods_nginx(target_url, date, dangerous), "nginx_methods")

    # Clickjacking
    if _is_issue(clickjacking_result):
        _write("nginx_clickjacking.conf", _build_clickjacking_nginx(target_url, date), "nginx_clickjacking")
        _write("fastapi_clickjacking.py", _build_clickjacking_fastapi(target_url, date), "fastapi_clickjacking")

    # Directory listing
    if _is_issue(directory_listing_result):
        raw_paths = (directory_listing_result or {}).get("exposed_paths", [])
        exposed = [p if isinstance(p, str) else p.get("path", "") for p in raw_paths]
        _write("nginx_directory_listing.conf", _build_directory_listing_nginx(target_url, date, exposed), "nginx_dirlist")

    # Open redirect
    if _is_issue(open_redirect_result):
        _write("fastapi_open_redirect.py", _build_open_redirect_fastapi(target_url, date), "fastapi_open_redirect")

    # Email security
    if _is_issue(email_result):
        _write("dns_email_security.txt", _build_email_security(target_url, date, email_result or {}), "dns_email")

    return generated
