from fastapi import APIRouter

from app.api.v1.endpoints import auth, vault, plans, subscriptions, sites, scans, webhooks, users, newsletter, url_scans, notifications, code_scans, nis2, iso27001, public_scans, blog, contact, bookings, admin_stats, admin_users, admin_scans, invoices, admin_invoices, admin_quotes, quotes, rssi

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(vault.router)
api_router.include_router(plans.router)
api_router.include_router(subscriptions.router)
api_router.include_router(sites.router)
api_router.include_router(scans.router)
api_router.include_router(webhooks.router)
api_router.include_router(users.router)
api_router.include_router(newsletter.router)
api_router.include_router(url_scans.router)
api_router.include_router(notifications.router)
api_router.include_router(code_scans.router)
api_router.include_router(nis2.router)
api_router.include_router(iso27001.router)
api_router.include_router(public_scans.router)
api_router.include_router(blog.router)
api_router.include_router(contact.router)
api_router.include_router(bookings.router)
api_router.include_router(admin_stats.router)
api_router.include_router(admin_users.router)
api_router.include_router(admin_scans.router)
api_router.include_router(invoices.router)
api_router.include_router(admin_invoices.router)
api_router.include_router(admin_quotes.router)
api_router.include_router(quotes.router)
api_router.include_router(rssi.router)
