from fastapi import APIRouter

from app.api.v1.endpoints import (
    admin_invoices,
    admin_quotes,
    admin_scans,
    admin_stats,
    admin_users,
    api_waitlist,
    auth,
    awareness,
    blog,
    bookings,
    brand,
    code_scans,
    collab,
    contact,
    cost_calc,
    darkweb,
    darkweb_dossier,
    invoices,
    iso27001,
    newsletter,
    nis2,
    notifications,
    pca,
    phishing,
    plans,
    public_scans,
    quiz,
    quotes,
    rssi,
    scans,
    sites,
    subscriptions,
    training,
    url_scans,
    users,
    vault,
    webhooks,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(vault.router)
api_router.include_router(plans.router)
api_router.include_router(subscriptions.router)
api_router.include_router(sites.router)
api_router.include_router(scans.router)
api_router.include_router(webhooks.router)
api_router.include_router(users.router)
api_router.include_router(newsletter.router)
api_router.include_router(url_scans.router)
api_router.include_router(notifications.router)
api_router.include_router(code_scans.router)
api_router.include_router(nis2.router)
api_router.include_router(iso27001.router)
api_router.include_router(public_scans.router)
api_router.include_router(blog.router)
api_router.include_router(contact.router)
api_router.include_router(bookings.router)
api_router.include_router(admin_stats.router)
api_router.include_router(admin_users.router)
api_router.include_router(admin_scans.router)
api_router.include_router(invoices.router)
api_router.include_router(admin_invoices.router)
api_router.include_router(admin_quotes.router)
api_router.include_router(quotes.router)
api_router.include_router(rssi.router)
api_router.include_router(training.router)
api_router.include_router(pca.router)
api_router.include_router(darkweb.router)
api_router.include_router(darkweb_dossier.router)
api_router.include_router(brand.router)
api_router.include_router(quiz.router)
api_router.include_router(cost_calc.router)
api_router.include_router(collab.router)
api_router.include_router(phishing.router)
api_router.include_router(api_waitlist.router)
api_router.include_router(awareness.router)
