"""plan stripe_price_id_yearly annual billing

Revision ID: 256304ec94d2
Revises: e4e037eb579f
Create Date: 2026-07-26 09:46:59.134539

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "256304ec94d2"
down_revision: str | None = "e4e037eb579f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans",
        sa.Column(
            "stripe_price_id_yearly", sa.String(length=255), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "stripe_price_id_yearly")
    # ### end Alembic commands ###
