"""origine du livrable : consultant ou client

Ouvre l etape 3 du depot de documents : jusqu ici seul le consultant deposait,
le portail client etait en lecture seule. Un livrable reste un livrable ; ce qui
change est qui l a produit.

Cette colonne n est pas cosmetique, elle porte DEUX REGIMES JURIDIQUES OPPOSES.
Un document depose par le CLIENT releve de la sous-traitance — art. 28-3-g du
RGPD : a la fin de la prestation, effacer OU RESTITUER, au choix du responsable
de traitement. Un livrable produit par le CONSULTANT est sa preuve en cas de
litige sur la qualite de la prestation, et doit survivre a la mission
(prescription de droit commun, 5 ans). Cf. docs/DEPOT_DOCUMENTS.md.

server_default a `consultant` : tout ce qui existe a ete depose par le
consultant, le portail client n ayant jamais rien permis d autre.

Revision ID: 3dfcf7b15156
Revises: 294593b3e4cc
Create Date: 2026-08-06 08:46:17.860941

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dfcf7b15156"
down_revision: str | None = "294593b3e4cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rssi_deliverables",
        sa.Column("origine", sa.String(length=20), server_default="consultant", nullable=False),
    )
    op.create_index(
        op.f("ix_rssi_deliverables_origine"), "rssi_deliverables", ["origine"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rssi_deliverables_origine"), table_name="rssi_deliverables")
    op.drop_column("rssi_deliverables", "origine")
    # ### end Alembic commands ###
