"""reconcile model schema drift

Aligne le schema reel (=prod) sur les modeles ORM pour que
`alembic revision --autogenerate` produise un diff VIDE. Sans ca, un futur
autogenerate pour un vrai changement embarquerait ces operations et un apply
naif pourrait droper des index utiles.

Surete verifiee sur RDS prod le 2026-07-17 (task ECS read-only) :
- NOT NULL : 0 NULL sur les 6 colonnes (check_status, checked_count,
  unverified_count, checked_at, rssi_clients.created_at, completed_at).
- token 512->64 : max(len)=64 (refresh) / table vide (password_reset).
- image_url TEXT->VARCHAR(1000) : table vide.
- unique constraint -> unique index : meme garantie, 0 doublon.

Revision ID: 46737f9d5ab4
Revises: 270a5783ec77
Create Date: 2026-07-17 17:03:29.045085

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46737f9d5ab4"
down_revision: str | None = "270a5783ec77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("api_waitlist_email_key", "api_waitlist", type_="unique")
    op.create_index(op.f("ix_api_waitlist_email"), "api_waitlist", ["email"], unique=True)
    op.drop_constraint("blog_posts_slug_key", "blog_posts", type_="unique")
    op.drop_index("ix_blog_posts_slug", table_name="blog_posts")
    op.create_index(op.f("ix_blog_posts_slug"), "blog_posts", ["slug"], unique=True)
    op.drop_constraint("bookings_cancel_token_key", "bookings", type_="unique")
    op.drop_index("ix_bookings_cancel_token", table_name="bookings")
    op.create_index(op.f("ix_bookings_cancel_token"), "bookings", ["cancel_token"], unique=True)
    op.alter_column(
        "darkweb_dossier_targets",
        "check_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "darkweb_dossiers",
        "checked_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "darkweb_dossiers",
        "unverified_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "darkweb_scans",
        "checked_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_constraint("uq_iso27001_assessments_user_id", "iso27001_assessments", type_="unique")
    op.alter_column(
        "newsletter_schedule_items",
        "image_url",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "token",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "refresh_tokens",
        "token",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "rssi_clients",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_constraint("site_collaborators_invite_token_key", "site_collaborators", type_="unique")
    op.drop_index("ix_site_collaborators_invite_token", table_name="site_collaborators")
    op.create_index(
        op.f("ix_site_collaborators_invite_token"),
        "site_collaborators",
        ["invite_token"],
        unique=True,
    )
    op.alter_column(
        "training_progress",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "training_progress",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_site_collaborators_invite_token"), table_name="site_collaborators")
    op.create_index(
        "ix_site_collaborators_invite_token", "site_collaborators", ["invite_token"], unique=False
    )
    op.create_unique_constraint(
        "site_collaborators_invite_token_key",
        "site_collaborators",
        ["invite_token"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "rssi_clients",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "refresh_tokens",
        "token",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "token",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "newsletter_schedule_items",
        "image_url",
        existing_type=sa.String(length=1000),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_unique_constraint(
        "uq_iso27001_assessments_user_id",
        "iso27001_assessments",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "darkweb_scans",
        "checked_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "darkweb_dossiers",
        "unverified_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "darkweb_dossiers",
        "checked_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "darkweb_dossier_targets",
        "check_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_index(op.f("ix_bookings_cancel_token"), table_name="bookings")
    op.create_index("ix_bookings_cancel_token", "bookings", ["cancel_token"], unique=False)
    op.create_unique_constraint(
        "bookings_cancel_token_key",
        "bookings",
        ["cancel_token"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_blog_posts_slug"), table_name="blog_posts")
    op.create_index("ix_blog_posts_slug", "blog_posts", ["slug"], unique=False)
    op.create_unique_constraint(
        "blog_posts_slug_key", "blog_posts", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_api_waitlist_email"), table_name="api_waitlist")
    op.create_unique_constraint(
        "api_waitlist_email_key", "api_waitlist", ["email"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
