"""registre des fichiers deposes et etat d analyse antivirus

Le depot de fichiers n'a jamais eu de registre : `storage.upload_file` ecrit un
objet et rend une cle, sans que rien ne garde trace de ce qui a ete stocke. Un
fichier televerse puis abandonne avant creation du livrable n'existe donc nulle
part en base — il occupe S3 sans titulaire ni date.

Cette table le corrige, et rend possibles les trois besoins de
`docs/DEPOT_DOCUMENTS.md` qui butaient dessus : l'etat d'analyse antivirus,
la retention (on n'efface pas ce dont on n'a pas trace) et le quota par client.

Table VIDE a la creation : les fichiers deja stockes n'y figurent pas. C'est
volontaire et le code en tient compte — un fichier sans ligne est traite comme
sain, faute de quoi ce deploiement rendrait indisponible chaque livrable deja
depose en production.

Revision ID: 56974e23d737
Revises: 3444e275c6ec
Create Date: 2026-08-03 10:59:44.671933

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56974e23d737"
down_revision: str | None = "3444e275c6ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fichiers_deposes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cle_stockage", sa.String(length=500), nullable=False),
        sa.Column("nom_original", sa.String(length=255), nullable=False),
        sa.Column("taille_octets", sa.Integer(), nullable=False),
        sa.Column("type_mime", sa.String(length=120), nullable=False),
        sa.Column("depose_par_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("statut_analyse", sa.String(length=20), nullable=False),
        sa.Column("analyse_le", sa.DateTime(timezone=True), nullable=True),
        sa.Column("depose_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["rssi_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["depose_par_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fichiers_deposes_cle_stockage"), "fichiers_deposes", ["cle_stockage"], unique=True
    )
    op.create_index(
        op.f("ix_fichiers_deposes_client_id"), "fichiers_deposes", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_fichiers_deposes_depose_le"), "fichiers_deposes", ["depose_le"], unique=False
    )
    op.create_index(
        op.f("ix_fichiers_deposes_depose_par_id"),
        "fichiers_deposes",
        ["depose_par_id"],
        unique=False,
    )
    op.create_index(op.f("ix_fichiers_deposes_id"), "fichiers_deposes", ["id"], unique=False)
    op.create_index(
        op.f("ix_fichiers_deposes_statut_analyse"),
        "fichiers_deposes",
        ["statut_analyse"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fichiers_deposes_statut_analyse"), table_name="fichiers_deposes")
    op.drop_index(op.f("ix_fichiers_deposes_id"), table_name="fichiers_deposes")
    op.drop_index(op.f("ix_fichiers_deposes_depose_par_id"), table_name="fichiers_deposes")
    op.drop_index(op.f("ix_fichiers_deposes_depose_le"), table_name="fichiers_deposes")
    op.drop_index(op.f("ix_fichiers_deposes_client_id"), table_name="fichiers_deposes")
    op.drop_index(op.f("ix_fichiers_deposes_cle_stockage"), table_name="fichiers_deposes")
    op.drop_table("fichiers_deposes")
    # ### end Alembic commands ###
