"""add vault_items

Revision ID: 5e6403bce97c
Revises: 12c7302c2a65
Create Date: 2026-04-01 09:39:16.251881

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5e6403bce97c"
down_revision: str | None = "12c7302c2a65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
