"""siren de l acheteur sur les factures

Revision ID: 81c3e7b3db68
Revises: e2f6f6cf56e6
Create Date: 2026-08-16 06:23:05.783441

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c3e7b3db68"
down_revision: str | None = "e2f6f6cf56e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("client_siren", sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "client_siren")
    # ### end Alembic commands ###
