"""add rssi_client_id to phishing_campaigns

Revision ID: 97647476457e
Revises: 46737f9d5ab4
Create Date: 2026-07-18 10:16:16.397138

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97647476457e"
down_revision: str | None = "46737f9d5ab4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phishing_campaigns", sa.Column("rssi_client_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_phishing_campaigns_rssi_client_id"),
        "phishing_campaigns",
        ["rssi_client_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_phishing_campaigns_rssi_client_id",
        "phishing_campaigns",
        "rssi_clients",
        ["rssi_client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_phishing_campaigns_rssi_client_id", "phishing_campaigns", type_="foreignkey"
    )
    op.drop_index(op.f("ix_phishing_campaigns_rssi_client_id"), table_name="phishing_campaigns")
    op.drop_column("phishing_campaigns", "rssi_client_id")
    # ### end Alembic commands ###
