"""add batch_size to phishing_campaigns

Revision ID: a08c087165b4
Revises: d04c845d0a5a
Create Date: 2026-07-18 14:52:00.291879

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a08c087165b4"
down_revision: str | None = "d04c845d0a5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phishing_campaigns", sa.Column("batch_size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phishing_campaigns", "batch_size")
    # ### end Alembic commands ###
