"""add training_on_fail to phishing_campaigns

Revision ID: d04c845d0a5a
Revises: 97647476457e
Create Date: 2026-07-18 14:14:06.673805

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d04c845d0a5a"
down_revision: str | None = "97647476457e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phishing_campaigns",
        sa.Column("training_on_fail", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "phishing_campaigns",
        sa.Column("training_trigger", sa.String(length=20), server_default="click", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phishing_campaigns", "training_trigger")
    op.drop_column("phishing_campaigns", "training_on_fail")
    # ### end Alembic commands ###
