"""add_category_to_vault_items

Revision ID: d397692772ea
Revises: f6a7b8c9d0e1
Create Date: 2026-04-08 13:34:59.988082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd397692772ea'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_items', sa.Column('category', sa.String(length=32), server_default='login', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_items', 'category')
    # ### end Alembic commands ###
