"""add url_scan_usages monotone quota counter (S3 #6)

Revision ID: d3b47ded55b3
Revises: 256304ec94d2
Create Date: 2026-07-29 09:36:43.578941

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3b47ded55b3"
down_revision: str | None = "256304ec94d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_scan_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_url_scan_usages_user_id"), "url_scan_usages", ["user_id"], unique=False
    )
    op.create_index(
        "ix_url_scan_usages_user_id_created_at",
        "url_scan_usages",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_url_scan_usages_user_id_created_at", table_name="url_scan_usages")
    op.drop_index(op.f("ix_url_scan_usages_user_id"), table_name="url_scan_usages")
    op.drop_table("url_scan_usages")
    # ### end Alembic commands ###
