"""preuves rattachees aux criteres nis2

Revision ID: e2f6f6cf56e6
Revises: 2a3bd12ceaea
Create Date: 2026-08-07 08:08:25.854356

Table de liaison : une piece justificative rattachee a un critere de conformite.
Une conformite sans preuve est une declaration ; avec preuves, c'est un dossier
opposable.

Elle pointe `fichiers_deposes` et non `rssi_deliverables` : le livrable est
propre au RSSI, le registre est commun aux deux parcours. C'est ce qui permet a
l'abonne qui veut NIS2 seul de rattacher ses propres pieces.

Creation de table uniquement — le `downgrade` genere est correct tel quel et n'a
pas ete repris, contrairement a celui de 2a3bd12ceaea.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2f6f6cf56e6"
down_revision: str | None = "2a3bd12ceaea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preuves_criteres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nis2_assessment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("fichier_id", sa.Integer(), nullable=False),
        sa.Column("rattache_le", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["fichier_id"], ["fichiers_deposes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["nis2_assessment_id"], ["nis2_assessments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "nis2_assessment_id",
            "item_id",
            "fichier_id",
            name="uq_preuves_criteres_evaluation_critere_fichier",
        ),
    )
    op.create_index(
        op.f("ix_preuves_criteres_fichier_id"), "preuves_criteres", ["fichier_id"], unique=False
    )
    op.create_index(op.f("ix_preuves_criteres_id"), "preuves_criteres", ["id"], unique=False)
    op.create_index(
        op.f("ix_preuves_criteres_item_id"), "preuves_criteres", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_preuves_criteres_nis2_assessment_id"),
        "preuves_criteres",
        ["nis2_assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preuves_criteres_rattache_le"), "preuves_criteres", ["rattache_le"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preuves_criteres_rattache_le"), table_name="preuves_criteres")
    op.drop_index(op.f("ix_preuves_criteres_nis2_assessment_id"), table_name="preuves_criteres")
    op.drop_index(op.f("ix_preuves_criteres_item_id"), table_name="preuves_criteres")
    op.drop_index(op.f("ix_preuves_criteres_id"), table_name="preuves_criteres")
    op.drop_index(op.f("ix_preuves_criteres_fichier_id"), table_name="preuves_criteres")
    op.drop_table("preuves_criteres")
    # ### end Alembic commands ###
