"""public_scans lead gate: email, consent, ip_hash, domain

Revision ID: e4e037eb579f
Revises: 5bd2b7bbc548
Create Date: 2026-07-26 09:06:54.523332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4e037eb579f"
down_revision: str | None = "5bd2b7bbc548"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("public_scans", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "public_scans", sa.Column("email_consent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("public_scans", sa.Column("ip_hash", sa.String(length=64), nullable=True))
    op.add_column("public_scans", sa.Column("domain", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_public_scans_email"), "public_scans", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_scans_email"), table_name="public_scans")
    op.drop_column("public_scans", "domain")
    op.drop_column("public_scans", "ip_hash")
    op.drop_column("public_scans", "email_consent_at")
    op.drop_column("public_scans", "email")
    # ### end Alembic commands ###
