"""date de cloture de mission, pour la retention des documents clients

Etape 4b du depot de documents. La retention des documents REMIS PAR LE CLIENT
part de la fin de prestation — art. 28-3-g du RGPD : le sous-traitant efface OU
RESTITUE, au choix du responsable de traitement.

`updated_at` ne pouvait pas servir de repere : il bouge a chaque modification,
donc une correction d adresse repousserait l echeance.

NUL POUR LES CLIENTS DEJA CLOS, ET C EST VOULU. Aucune date n est inventee
retroactivement : on ne detruit pas de donnees sur la foi d un repere fabrique.
C est sans consequence — le depot cote client n existe que depuis le 2026-08-05,
donc aucune mission close avant cette date ne peut porter de document `client`.


Revision ID: e59d0ef982d0
Revises: 3dfcf7b15156
Create Date: 2026-08-06 10:36:55.426345

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e59d0ef982d0"
down_revision: str | None = "3dfcf7b15156"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rssi_clients", sa.Column("cloture_le", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_rssi_clients_cloture_le"), "rssi_clients", ["cloture_le"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rssi_clients_cloture_le"), table_name="rssi_clients")
    op.drop_column("rssi_clients", "cloture_le")
    # ### end Alembic commands ###
