"""Phishing templates — email HTML templates, landing pages, awareness pages.
Pure functions and constants, no DB dependency."""

from .emails import (
    _SCENARIO_TEMPLATES,
    SCENARIO_LABELS,
    _tpl_bank,
    _tpl_ceo_fraud,
    _tpl_fake_invoice,
    _tpl_hr_document,
    _tpl_invoice_pdf,
    _tpl_it_password,
    _tpl_it_ticket,
    _tpl_o365,
    _tpl_parcel,
    _tpl_prize,
    _tpl_sharepoint,
    _tpl_teams,
    _tpl_vpn_update,
)
from .engine import (
    _attachment_badge,
    _dynamic_ctx,
    _email_wrap,
)
from .landings import (
    _DEFAULT_SCENARIO_KEY,
    _LANDING_BANK,
    _LANDING_CEO,
    _LANDING_DOCUSIGN,
    _LANDING_HR,
    _LANDING_IT,
    _LANDING_MICROSOFT,
    _LANDING_PARCEL,
    _LANDING_PAYMENT,
    _LANDING_PRIZE,
    _LANDING_TEMPLATES,
    _PIXEL_GIF,
    _SCENARIO_AWARENESS,
    _SCENARIO_LANDING,
    get_awareness_html,
    get_expired_html,
    get_landing_html,
    get_pixel_gif,
)

__all__ = [
    "_DEFAULT_SCENARIO_KEY",
    "_LANDING_BANK",
    "_LANDING_CEO",
    "_LANDING_DOCUSIGN",
    "_LANDING_HR",
    "_LANDING_IT",
    "_LANDING_MICROSOFT",
    "_LANDING_PARCEL",
    "_LANDING_PAYMENT",
    "_LANDING_PRIZE",
    "_LANDING_TEMPLATES",
    "_PIXEL_GIF",
    "_SCENARIO_AWARENESS",
    "_SCENARIO_LANDING",
    "_SCENARIO_TEMPLATES",
    "SCENARIO_LABELS",
    "_attachment_badge",
    "_dynamic_ctx",
    "_email_wrap",
    "get_awareness_html",
    "get_expired_html",
    "get_landing_html",
    "get_pixel_gif",
    "_tpl_bank",
    "_tpl_ceo_fraud",
    "_tpl_fake_invoice",
    "_tpl_hr_document",
    "_tpl_invoice_pdf",
    "_tpl_it_password",
    "_tpl_it_ticket",
    "_tpl_o365",
    "_tpl_parcel",
    "_tpl_prize",
    "_tpl_sharepoint",
    "_tpl_teams",
    "_tpl_vpn_update",
]
